### ISSUE TITLE
Fix docker-compose to use nginx pulled from Docker Hub 

### ISSUE THREAD

**Issue by SDiamante13** [chance-nelson/SnowStorm#13]
Currently while running `docker-compose up -d` an error is thrown: `nginx either does not exist, is not accessible, or is not a valid URL.`

**Comment by chance-nelson** [comment]
Woops, forgot to remove that container from the docker compose. We will need a custom config for the nginx container if we want to route through it, or we can just remove that entirely, and leave it up to people after deployment if they want it.
