### ISSUE TITLE
Add setup.py

### ISSUE THREAD

**Issue by chance-nelson** [chance-nelson/SnowStorm#5]
Add a `setup.py` file, which defines packages for both the `stream` and `api` modules.

**Comment by eudanilolira** [comment]
Hi, can you explain more about it ?

**Comment by chance-nelson** [comment]
Hi @DaniloLira! Most python projects create a `setup.py` file, in the root directory on their repo. This script helps define information on the modules provided by the project (in this case, we are providing two modules: `api` and `stream`). [You may find this guide useful](https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/quickstart.html) if you'd like to take a crack at adding one to this repo.
